### ISSUE TITLE
Demo link leads to a 404 error page

### ISSUE THREAD

**Issue by mudrd8mz** [bizDevelop/moodle-mod_bizexaminer#6]
Using the link in the plugin description https://www.bizexaminer.com/en/#demo leads to a 404 error page:

![image](https://github.com/bizDevelop/moodle-mod_bizexaminer/assets/85831/753f5e5d-01b8-4c7a-92ef-378d01c0db22)

**Comment by gaambo** [comment]
Fixed in [v1.3.0](https://github.com/bizDevelop/moodle-mod_bizexaminer/releases/tag/v1.3.0)

**Comment by danmarsden** [comment]
this is still an issue in the moodle.org plugins db description. the link at the top of the description gives a 404 error.
